name: Loomvale Sheet Bot

on:
  schedule:
    - cron: "0 9 */2 * *"  # Every 2 days at 09:00 UTC
  workflow_dispatch:       # Manual trigger option

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Loomvale Sheet Bot
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CX_ID: ${{ secrets.GOOGLE_CX_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          PIPELINE_TAB: ${{ secrets.PIPELINE_TAB }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_URL: ${{ secrets.HF_SPACE_URL }}
          HF_MODEL: ${{ secrets.HF_MODEL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python loomvale_sheet_bot.py
