name: Loomvale Cron

on:
  schedule:
    - cron: "0 9 */2 * *"   # every 2 days @ 09:00 UTC
  workflow_dispatch: {}

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Google credentials
        # Use printf to avoid trailing newline issues
        run: printf '%s' "$GOOGLE_CREDENTIALS_JSON" > credentials.json
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Run Loomvale bot
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CX_ID: ${{ secrets.GOOGLE_CX_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
        run: python loomvale_sheet_bot.py
