name: Loomvale Hugging Face Worker

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:

jobs:
  generate-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Hugging Face Worker
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          PIPELINE_TAB: ${{ secrets.PIPELINE_TAB }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_MODEL: ${{ secrets.HF_MODEL }}
          MODE: generate
        run: |
          python loomvale_sheet_bot.py
