name: Loomvale Sheet Bot

on:
  workflow_dispatch:      # 👈 Enables manual run button
  schedule:
    - cron: "0 9 */2 * *"  # Runs every 2 days at 09:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Loomvale Sheet Bot
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_CX_ID: ${{ secrets.GOOGLE_CX_ID }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_MODEL: ${{ secrets.HF_MODEL }}
          PIPELINE_TAB: ${{ secrets.PIPELINE_TAB }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python loomvale_sheet_bot.py
