name: Loomvale Sheet Bot

on:
  schedule:
    - cron: "0 9 */2 * *"   # every 2 days @ 09:00 UTC
  workflow_dispatch: {}      # allows manual run button

permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Loomvale Sheet Bot
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CX_ID: ${{ secrets.GOOGLE_CX_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          PIPELINE_TAB: ${{ secrets.PIPELINE_TAB }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_MODEL: ${{ secrets.HF_MODEL }}
          HF_SPACE_URL: ${{ secrets.HF_SPACE_URL }}
        run: python loomvale_sheet_bot.py
