name: Loomvale Sheet Bot

on:
  schedule:
    - cron: "0 9 */2 * *"   # every 2 days at 09:00 UTC
  workflow_dispatch:        # enables manual run
    inputs:
      debug:
        description: "Run in debug mode (process 1 row)"
        required: false
        default: "false"

permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Loomvale Sheet Bot
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CX_ID: ${{ secrets.GOOGLE_CX_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          PIPELINE_TAB: ${{ secrets.PIPELINE_TAB }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_MODEL: ${{ secrets.HF_MODEL }}
          DEBUG_MODE: ${{ github.event.inputs.debug }}
        run: |
          echo "🔹 Starting Loomvale Sheet Bot..."
          echo "⏰ Timestamp: $(date)"
          echo "🐍 Python version:"
          python --version
          echo "📦 Installed dependencies:"
          pip list
          echo "🚀 Running sheet bot..."
          python loomvale_sheet_bot.py || echo "❌ Script exited with error."
          echo "✅ Workflow finished."
